spring.application.name=audit-service

server.port = 4005

spring.data.mongodb.uri=mongodb://localhost:27017/audit_db


spring.kafka.consumer.properties.spring.json.trusted.packages=com.shopping.audit_service.dto

