server:
  port: 4001

auth:
  service:
    url: http://localhost:4002/user

logging:
  pattern:
    level: '%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]'
  level:
    io:
      micrometer:
        tracing: DEBUG
management:
  tracing:
    sampling:
      probability: '1.0'
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces


spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: http://localhost:4002
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        # Route for /api/items/** to item-service
        - id: item-service-route
          uri: http://localhost:4003
          predicates:
            - Path=/api/api/items/**
          filters:
            - StripPrefix=1
            - JwtValidation
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST



