server:
  port: 4001

auth:
  service:
    url: http://localhost:4002/user

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: http://localhost:4002
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        # Route for /api/items/** to item-service
        - id: item-service-route
          uri: http://localhost:4003
          predicates:
            - Path=/api/api/items/**
          filters:
            - StripPrefix=1
            - JwtValidation



