server:
  port: '4002'

springdoc:
  swagger-ui:
    path: /user-swagger-ui
  api-docs:
    path: /test-api-docs
jwt:
  secret: Y2FwdGFpbndpbGx3aW5pbmRvY3RvcmRvb213aXRodGhvcmFuZERvY3RvclN0cmFuZ2U=


management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    enabled: 'true'
    sampling:
      probability: '1.0'
  otlp:
    tracing:
      transport: http
      endpoint: http://localhost:4318/v1/traces
  observations:
    http:
      server:
        requests:
          enabled: 'true'
spring:
  security:
    filter:
      order: '5'
  application:
    name: service
  h2:
    console:
      path: /h2-console
  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    password: root
    driver-class-name: org.h2.Driver
    username: rohit
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always

logging:
  pattern:
    level: '%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]'
  level:
    io:
      micrometer:
        tracing: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:4006/eureka
    register-with-eureka: true
    fetch-registry: true
