spring.application.name=service
server.port=4002
spring.security.filter.order=5
management.tracing.sampling.probability=1.0
# Use 4317 for gRPC or 4318 for HTTP
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.otlp.tracing.transport=http
management.endpoints.web.exposure.include=*
management.tracing.enabled=true
management.observations.http.server.requests.enabled=true
logging.pattern.level=%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]
logging.level.io.micrometer.tracing=DEBUG


springdoc.api-docs.path=/test-api-docs
springdoc.swagger-ui.path=/user-swagger-ui

spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=rohit
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

jwt.secret=Y2FwdGFpbndpbGx3aW5pbmRvY3RvcmRvb213aXRodGhvcmFuZERvY3RvclN0cmFuZ2U=



