spring.application.name=order-service
server.port =4004

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

spring.kafka.consumer.properties.spring.json.trusted.packages=com.shopping.order_service.external.dto
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.linger.ms=10
spring.kafka.producer.properties.batch-size=16384

eureka.client.service-url.defaultZone=http://localhost:4006/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
