spring.application.name=eureka-service



eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Point the internal client to the correct server port
eureka.client.service-url.defaultZone=http://localhost:8080/eureka/
