spring.application.name=item-service

server.port =4003

management.tracing.sampling.probability=1.0
# Use 4317 for gRPC or 4318 for HTTP
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
logging.pattern.level=%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]
logging.level.io.micrometer.tracing=DEBUG

springdoc.api-docs.path=/test-api-docs
springdoc.swagger-ui.path=/user-swagger-ui


#MySql Database Configurations
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/shopping
spring.datasource.username=root
spring.datasource.password=Rohit@2510
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

eureka.client.service-url.defaultZone=http://localhost:4006/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

